"use client";
import {useMemo,useState} from "react";
type Crop={id:string;name:string;short:string;color:string;kind:"berry"|"resource";yieldPerPlant:number;minutes:number;recipe?:number};
const CROPS:Crop[]=[
{id:"blue",name:"Berries azules",short:"Azul",color:"#5d8cff",kind:"berry",yieldPerPlant:10,minutes:120,recipe:32},{id:"yellow",name:"Berries amarillas",short:"Amarilla",color:"#eabf45",kind:"berry",yieldPerPlant:10,minutes:120,recipe:32},{id:"red",name:"Berries rojas",short:"Roja",color:"#ef665b",kind:"berry",yieldPerPlant:10,minutes:120,recipe:32},{id:"green",name:"Berries verdes",short:"Verde",color:"#66c477",kind:"berry",yieldPerPlant:10,minutes:120,recipe:32},{id:"white",name:"Berries blancas",short:"Blanca",color:"#d9dfd5",kind:"berry",yieldPerPlant:10,minutes:120,recipe:32},{id:"hemp",name:"Cloth (cáñamo)",short:"Cloth",color:"#b7d06e",kind:"resource",yieldPerPlant:1200,minutes:120},{id:"corn",name:"Maíz",short:"Maíz",color:"#f19c4b",kind:"resource",yieldPerPlant:60,minutes:120},{id:"pumpkin",name:"Calabaza",short:"Calabaza",color:"#df793f",kind:"resource",yieldPerPlant:60,minutes:120}];
const fmt=(v:number,d=0)=>new Intl.NumberFormat("es-CL",{maximumFractionDigits:d}).format(v||0);
export default function Home(){
 const[cropId,setCropId]=useState("blue"),[modules,setModules]=useState(5),[planters,setPlanters]=useState(8),[plants,setPlants]=useState(9),[yieldPerPlant,setYield]=useState(10),[minutes,setMinutes]=useState(120),[harvests,setHarvests]=useState(2),[recipe,setRecipe]=useState(32);const[rows,setRows]=useState<{crop:Crop;modules:number}[]>([]);const crop=CROPS.find(c=>c.id===cropId)!;
 const r=useMemo(()=>{const totalPlanters=modules*planters,totalPlants=totalPlanters*plants,perHarvest=totalPlants*yieldPerPlant,perDay=perHarvest*harvests;return{totalPlanters,totalPlants,perHarvest,perDay,perHour:perHarvest/(minutes/60),teas:recipe?perHarvest/recipe:0,teasDay:recipe?perDay/recipe:0}},[modules,planters,plants,yieldPerPlant,minutes,harvests,recipe]);
 const choose=(id:string)=>{const c=CROPS.find(x=>x.id===id)!;setCropId(id);setYield(c.yieldPerPlant);setMinutes(c.minutes);setRecipe(c.recipe??0)};
 return <main><header className="topbar"><a className="brand" href="#top"><span className="brandMark">RF</span>RUST FARM LAB</a><nav><a href="#calculator">Calculadora</a><a href="#planner">Plan de granja</a></nav><span className="serverBadge"><i/> Datos ajustables</span></header>
 <section className="hero" id="top"><div className="eyebrow"><span>●</span> CALCULADORA DE PRODUCCIÓN</div><h1>Planifica cada cosecha.<br/><em>Domina el wipe.</em></h1><p>Calcula la producción real de tus módulos, compara cultivos y convierte berries en tés antes de construir.</p><div className="heroStats"><div><b>9</b><span>plantas por planter</span></div><div><b>8</b><span>planters por módulo</span></div><div><b>100%</b><span>valores editables</span></div></div></section>
 <section className="workspace" id="calculator"><Heading n="01" title="Arma tu cultivo" text="Usa los valores sugeridos o reemplázalos por los de tu genética y servidor."/><div className="cropStrip">{CROPS.map(c=><button key={c.id} onClick={()=>choose(c.id)} className={cropId===c.id?"crop active":"crop"} style={{"--crop":c.color} as React.CSSProperties}><span className="cropDot"/><small>{c.kind==="berry"?"BERRY":"RECURSO"}</small><b>{c.short}</b></button>)}</div>
 <div className="calculatorGrid"><div className="controlPanel"><Stepper label="Módulos" hint="salas de cultivo" value={modules} set={setModules}/><Stepper label="Planters por módulo" hint="large planters" value={planters} set={setPlanters}/><Stepper label="Plantas por planter" hint="máximo habitual: 9" value={plants} set={setPlants} max={9}/><div className="twoCols"><Field label="Rendimiento / planta" value={yieldPerPlant} set={setYield}/><Field label="Minutos / ciclo" value={minutes} set={setMinutes}/><Field label="Cosechas / día" value={harvests} set={setHarvests} step={.5}/><Field label="Unidades / té" value={recipe} set={setRecipe} disabled={crop.kind!=="berry"}/></div><button className="addButton" onClick={()=>setRows(x=>[...x,{crop,modules}])}>+ Agregar al plan de granja</button></div>
 <aside className="resultPanel"><div className="resultTop"><span>PRODUCCIÓN ESTIMADA</span><span className="live">EN VIVO</span></div><div className="primaryResult"><span style={{background:crop.color}}/><div><small>POR COSECHA</small><strong>{fmt(r.perHarvest)}</strong><p>{crop.name}</p></div></div><div className="resultMetrics"><Metric l="Por hora" v={fmt(r.perHour,1)}/><Metric l="Por día" v={fmt(r.perDay)}/><Metric l="Total planters" v={fmt(r.totalPlanters)}/><Metric l="Total plantas" v={fmt(r.totalPlants)}/></div>{crop.kind==="berry"&&<div className="teaCard"><div><small>TÉS POR COSECHA</small><b>{fmt(r.teas,1)}</b></div><div><small>TÉS POR DÍA</small><b>{fmt(r.teasDay,1)}</b></div><p>Conversión simple usando {recipe} berries por té. Puedes cambiar la receta para tés mixtos.</p></div>}<div className="formula">{modules} módulos × {planters} planters × {plants} plantas × {fmt(yieldPerPlant)} rendimiento</div></aside></div></section>
 <section className="planner" id="planner"><Heading n="02" title="Tu plan de granja" text="Agrega escenarios desde la calculadora y construye tu distribución ideal."/>{rows.length===0?<div className="empty"><span>＋</span><b>Aún no agregas cultivos</b><p>Configura un cultivo arriba y agrégalo al plan.</p></div>:<div className="planTable"><div className="planHead"><span>Cultivo</span><span>Módulos</span><span>Planters</span><span>Producción / cosecha</span><span/></div>{rows.map((row,i)=><div className="planRow" key={i}><span><i style={{background:row.crop.color}}/>{row.crop.name}</span><b>{row.modules}</b><span>{row.modules*planters}</span><strong>{fmt(row.modules*planters*plants*row.crop.yieldPerPlant)}</strong><button aria-label="Eliminar" onClick={()=>setRows(rows.filter((_,j)=>j!==i))}>×</button></div>)}<div className="planFoot"><span>{rows.reduce((s,x)=>s+x.modules,0)} módulos planificados</span><button onClick={()=>setRows([])}>Limpiar plan</button></div></div>}</section>
 <footer><span>RUST FARM LAB</span><p>Herramienta comunitaria no afiliada a Facepunch Studios.</p><a href="#top">Volver arriba ↑</a></footer></main>}
function Heading({n,title,text}:{n:string;title:string;text:string}){return <div className="sectionHeading"><div><span className="kicker">{n} — CONFIGURACIÓN</span><h2>{title}</h2></div><p>{text}</p></div>}
function Stepper({label,hint,value,set,max=99}:{label:string;hint:string;value:number;set:(n:number)=>void;max?:number}){return <div className="stepperRow"><div><label>{label}</label><small>{hint}</small></div><div className="stepper"><button onClick={()=>set(Math.max(1,value-1))}>−</button><input aria-label={label} type="number" min="1" max={max} value={value} onChange={e=>set(Math.min(max,Math.max(1,+e.target.value)))}/><button onClick={()=>set(Math.min(max,value+1))}>+</button></div></div>}
function Field({label,value,set,step=1,disabled=false}:{label:string;value:number;set:(n:number)=>void;step?:number;disabled?:boolean}){return <label className={disabled?"field disabled":"field"}><span>{label}</span><input type="number" min="0" step={step} disabled={disabled} value={value} onChange={e=>set(Math.max(0,+e.target.value))}/></label>}
function Metric({l,v}:{l:string;v:string}){return <div><small>{l}</small><b>{v}</b></div>}
